version: "3.8"

services:
  app:
    image: ghcr.io/sysxtreme/production-example:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      NODE_ENV: production
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.production-example.rule=Host(`myapp.acphost.xyz`)"
      - "traefik.http.routers.production-example.entrypoints=websecure"
      - "traefik.http.routers.production-example.tls=true"
      - "traefik.http.services.production-example.loadbalancer.server.port=3000"

networks:
  web:
    external: true  # Assume you're using Dokploy's default Traefik network
